#!/bin/bash

# need to add writes to log file
# check if input is install
if [ "$1" = "install" ]
then
    # install dependencies
    npm install typescript &> './dev/null'
    npm install typescript ts-node &> './dev/null'
    npm install axios &> './dev/null'
    npm install winston &> './dev/null'
    npm install dotenv &> './dev/null'
    # add check for successful install
    echo "4 dependencies installed"
    # need to change exit code to be based on if install was successful
    exit 0

# check if input is a file
elif [ -f "$1" ]
then
    tsc *.ts
    node main.js "$1"
    exit 0

# check if input is test
elif [ "$1" = "test" ]
then
    echo "Running the test suite"
    #insert call to test suite
    exit 0

# invalid input
else
    echo "Please enter a valid argument: ./run <URL_FILE> ./run test ./run install"
    exit 1
fi